#!/usr/bin/env python3
"""Run RTL cycle sweeps for PageRank global-source K-stage wavefront.

This script answers the practical stage-depth question for the current
PageRank mode4 RTL.  It does not use the prior fractional MSDF_MUL_ADD_8
contract; it sizes the solver-native global-source wavefront implementation.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess


ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parent
OUT_DIR = ROOT / "generated"

COUNTER_RE = re.compile(
    r"COUNTERS\s+(?P<label>\S+)\s+"
    r"total=(?P<total>\d+)\s+"
    r"issue=(?P<issue>\d+)\s+"
    r"cert_wait=(?P<cert_wait>\d+)\s+"
    r"iter=(?P<iters>\d+)"
)


def rtl_sources() -> list[str]:
    return [str(p) for p in sorted((ROOT / "rtl").glob("*.v"))]


def run_case(stages: int) -> dict[str, int | float | str]:
    if stages < 2:
        raise ValueError("mode4 RTL requires at least two stages")

    out = pathlib.Path("/tmp") / f"tb_pagerank_wavefront_k{stages}.vvp"
    cmd = [
        "iverilog",
        "-g2012",
        "-I",
        str(ROOT / "tb"),
        f"-DWAVEFRONT_SUPERSTEP_STAGES_VALUE={stages}",
        "-DPAGERANK32_GLOBAL",
        "-DPAGERANK32_WAVEFRONT_RUNTIME",
        "-DJACOBI32_NUM_ITERS_VALUE=1",
        f"-DJACOBI32_NUM_GOLD_ITERS_VALUE={stages}",
        "-o",
        str(out),
    ]
    cmd.extend(rtl_sources())
    cmd.append(str(ROOT / "tb/tb_iter_dense_runtime_jacobi32_blockdiag_multi.v"))

    subprocess.run(cmd, cwd=REPO, check=True, capture_output=True, text=True)
    sim = subprocess.run(["vvp", str(out)], cwd=REPO, check=True, capture_output=True, text=True)
    match = COUNTER_RE.search(sim.stdout)
    if not match:
        raise RuntimeError(f"missing COUNTERS line for K={stages}\n{sim.stdout}")

    total = int(match.group("total"))
    issue = int(match.group("issue"))
    cert_wait = int(match.group("cert_wait"))
    # Conventional full-wait reference for K PageRank iterations on the same
    # fixture.  Current P4 fractional/full-digit single-iteration issue path
    # finishes in 135 cycles for four iterations, i.e. 33.75 cycles/iter in the
    # testbench counter domain.  Use the direct model below for stage-depth
    # judgement and keep this RTL table as measured absolute cycles.
    return {
        "stages": stages,
        "total": total,
        "issue": issue,
        "cert_wait": cert_wait,
        "iters": int(match.group("iters")),
        "cycles_per_fused_iter": total / stages,
        "label": match.group("label"),
    }


def write_report(rows: list[dict[str, int | float | str]]) -> pathlib.Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report = OUT_DIR / "pagerank_wavefront_stage_sweep.md"
    lines = [
        "# PageRank Wavefront Stage Sweep",
        "",
        "This report is generated by `run_pagerank_wavefront_stage_sweep.py`.",
        "It measures the current global-source `ROW_DATAPATH_MODE=4` PageRank",
        "wavefront RTL.  This is the solver-native integer/full-digit fixture,",
        "not the strict prior-fractional `MSDF_MUL_ADD_8` contract.",
        "",
        "| K stages | total cycles | issue cycles | cert-wait cycles | fused iterations | cycles/fused iter |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['stages']} | {row['total']} | {row['issue']} | "
            f"{row['cert_wait']} | {row['stages']} | "
            f"{row['cycles_per_fused_iter']:.2f} |"
        )
    lines.extend(
        [
            "",
            "## Stage-Depth Decision",
            "",
            "- K=2 proves the basic direct digit handoff, but is too small for a paper-level solver checkpoint.",
            "- K=3 is legal but awkward for power-of-two banking and gives less architectural contrast.",
            "- K=4 is the first recommended RTL target: it fuses four PageRank iterations, matches the current four-iteration golden fixture, and keeps resource growth bounded.",
            "- K=8 should be evaluated only after regenerating an eight-iteration PageRank fixture and routing K=4 on U55C; it is a scale checkpoint, not the first implementation target.",
            "",
            "Current conclusion: **implement and route K=4 first**.  Deeper cascade is justified only if K=4 has positive WNS and the measured cycles/fused-iteration trend remains favorable.",
            "",
        ]
    )
    report.write_text("\n".join(lines), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stages", type=int, action="append", default=[2, 3, 4])
    args = parser.parse_args()

    rows = [run_case(k) for k in args.stages]
    report = write_report(rows)
    for row in rows:
        print(
            f"K={row['stages']} total={row['total']} issue={row['issue']} "
            f"cert_wait={row['cert_wait']} cycles_per_fused_iter="
            f"{row['cycles_per_fused_iter']:.2f}"
        )
    print(f"Wrote {report.relative_to(REPO)}")


if __name__ == "__main__":
    main()
