#!/usr/bin/env python3
"""Run Icarus sweeps for committed-state wavefront digit streaming."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess


ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parent
OUT_DIR = ROOT / "generated"

RTL_SOURCES = [
    "rtl/iter_wavefront_radius1_commit_multistage_cluster.v",
    "rtl/iter_wavefront_commit_stage_cluster.v",
    "rtl/iter_wavefront_digit_delay_line.v",
    "rtl/iter_solver_native_commit_adapter.v",
    "rtl/iter_solver_native_row_digit_engine.v",
    "rtl/iter_streamed_bias_source.v",
    "rtl/iter_online_affine_no_bias_core.v",
    "rtl/iter_const_coeff_digit_contrib_rail.v",
    "rtl/iter_parallel_online_adder_4_with_obuf.v",
    "rtl/iter_parallel_online_adder_4.v",
    "rtl/iter_parallel_online_adder.v",
    "rtl/iter_parallel_online_adder_block.v",
    "rtl/iter_full_adder.v",
    "rtl/iter_dff.v",
    "rtl/iter_online_affine_digit_core.v",
    "rtl/iter_online_output_update.v",
    "tb/tb_iter_wavefront_radius1_commit_multistage_cluster.v",
]

INFO_RE = re.compile(
    r"INFO commit stages=(?P<stages>\d+) "
    r"skip=(?P<skip>\d+) "
    r"delay=(?P<delay>\d+) "
    r"wavefront_done_cycle=(?P<wavefront>\d+) "
    r"fullwait_model_cycle=(?P<fullwait>\d+) "
    r"saved_cycles=(?P<saved>-?\d+)"
)


def run_case(
    num_stages: int, data_width: int, skip_digits: int, inter_stage_delay: int
) -> dict[str, int | float]:
    out = pathlib.Path("/tmp") / (
        f"tb_iter_wavefront_radius1_commit_multistage_cluster"
        f"_k{num_stages}_d{data_width}_s{skip_digits}_f{inter_stage_delay}.vvp"
    )
    compile_cmd = [
        "iverilog",
        "-g2012",
        "-P",
        f"tb_iter_wavefront_radius1_commit_multistage_cluster.NUM_STAGES={num_stages}",
        "-P",
        f"tb_iter_wavefront_radius1_commit_multistage_cluster.DATA_WIDTH={data_width}",
        "-P",
        f"tb_iter_wavefront_radius1_commit_multistage_cluster.SKIP_DIGITS={skip_digits}",
        "-P",
        "tb_iter_wavefront_radius1_commit_multistage_cluster."
        f"INTER_STAGE_DELAY_CYCLES={inter_stage_delay}",
        "-o",
        str(out),
    ]
    compile_cmd.extend(str(ROOT / src) for src in RTL_SOURCES)
    subprocess.run(compile_cmd, cwd=REPO, check=True, capture_output=True, text=True)
    sim = subprocess.run(["vvp", str(out)], cwd=REPO, check=True, capture_output=True, text=True)
    match = INFO_RE.search(sim.stdout)
    if not match:
        raise RuntimeError(
            f"missing INFO line for K={num_stages}, D={data_width}, "
            f"skip={skip_digits}, delay={inter_stage_delay}\n{sim.stdout}"
        )
    wavefront = int(match.group("wavefront"))
    fullwait = int(match.group("fullwait"))
    saved = int(match.group("saved"))
    return {
        "num_stages": num_stages,
        "data_width": data_width,
        "skip_digits": skip_digits,
        "inter_stage_delay": inter_stage_delay,
        "wavefront": wavefront,
        "fullwait": fullwait,
        "saved": saved,
        "speedup": fullwait / wavefront,
    }


def parse_cases(raw_cases: list[str]) -> list[tuple[int, int, int, int]]:
    cases: list[tuple[int, int, int, int]] = []
    for raw in raw_cases:
        parts = raw.lower().split("x")
        if len(parts) == 3:
            k_s, d_s, skip_s = parts
            delay_s = "0"
        elif len(parts) == 4:
            k_s, d_s, skip_s, delay_s = parts
        else:
            raise ValueError(f"bad case '{raw}', expected KxDxS or KxDxSxF")
        cases.append((int(k_s), int(d_s), int(skip_s), int(delay_s)))
    return cases


def write_report(rows: list[dict[str, int | float]]) -> pathlib.Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report = OUT_DIR / "wavefront_commit_stream_sweep.md"
    lines = [
        "# Committed-State Wavefront Digit-Stream Sweep",
        "",
        "This report is generated by `run_wavefront_commit_sweep.py`.",
        "It uses the commit-aware K-stage radius-1 cluster, so every inter-stage",
        "edge carries the same fixed-width digit stream that mode3 would write",
        "to the state bank.",
        "",
        "| stages K | data width D | skip digits | inter-stage delay | wavefront cycles | full-wait cycles | saved cycles | speedup |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['num_stages']} | {row['data_width']} | {row['skip_digits']} | "
            f"{row['inter_stage_delay']} | {row['wavefront']} | {row['fullwait']} | "
            f"{row['saved']} | {row['speedup']:.3f}x |"
        )
    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- This is the correct runtime-adjacent contract: raw row-engine digits",
            "  are not forwarded until the commit adapter has skipped the online",
            "  warm-up digits.",
            "- The speedup is lower than the raw-stream proof, but it still grows",
            "  with K because full-wait replay pays the commit boundary once per",
            "  solver iteration.",
            "- This remains an Icarus cycle checkpoint; U55C route must be run after",
            "  runtime mode integration.",
            "",
        ]
    )
    report.write_text("\n".join(lines), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--case",
        action="append",
        default=["2x8x4", "4x8x4", "8x8x4", "4x11x4", "8x11x4", "4x8x4x1"],
        help="case formatted as KxDxS or KxDxSxF",
    )
    args = parser.parse_args()
    rows = [run_case(k, d, s, f) for k, d, s, f in parse_cases(args.case)]
    report = write_report(rows)
    for row in rows:
        print(
            f"K={row['num_stages']} D={row['data_width']} skip={row['skip_digits']} "
            f"delay={row['inter_stage_delay']} wavefront={row['wavefront']} "
            f"fullwait={row['fullwait']} speedup={row['speedup']:.3f}x"
        )
    print(f"Wrote {report.relative_to(REPO)}")


if __name__ == "__main__":
    main()
