#!/usr/bin/env python3
"""Run directed Icarus sweeps for the wavefront digit-stream cluster."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess


ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parent
OUT_DIR = ROOT / "generated"

RTL_SOURCES = [
    "rtl/iter_wavefront_radius1_multistage_cluster.v",
    "rtl/iter_wavefront_digit_delay_line.v",
    "rtl/iter_solver_native_row_digit_engine.v",
    "rtl/iter_streamed_bias_source.v",
    "rtl/iter_online_affine_no_bias_core.v",
    "rtl/iter_const_coeff_digit_contrib_rail.v",
    "rtl/iter_parallel_online_adder_4_with_obuf.v",
    "rtl/iter_parallel_online_adder_4.v",
    "rtl/iter_parallel_online_adder.v",
    "rtl/iter_parallel_online_adder_block.v",
    "rtl/iter_full_adder.v",
    "rtl/iter_dff.v",
    "rtl/iter_online_affine_digit_core.v",
    "rtl/iter_online_output_update.v",
    "tb/tb_iter_wavefront_radius1_multistage_cluster.v",
]

INFO_RE = re.compile(
    r"INFO stages=(?P<stages>\d+) "
    r"(?:delay=(?P<delay>\d+) )?"
    r"wavefront_done_cycle=(?P<wavefront>\d+) "
    r"fullwait_model_cycle=(?P<fullwait>\d+) "
    r"saved_cycles=(?P<saved>-?\d+)"
)


def run_case(
    num_stages: int, data_width: int, inter_stage_delay: int
) -> dict[str, int | float | str]:
    out = pathlib.Path("/tmp") / (
        f"tb_iter_wavefront_radius1_multistage_cluster"
        f"_k{num_stages}_d{data_width}_f{inter_stage_delay}.vvp"
    )
    compile_cmd = [
        "iverilog",
        "-g2012",
        "-P",
        f"tb_iter_wavefront_radius1_multistage_cluster.NUM_STAGES={num_stages}",
        "-P",
        f"tb_iter_wavefront_radius1_multistage_cluster.DATA_WIDTH={data_width}",
        "-P",
        "tb_iter_wavefront_radius1_multistage_cluster."
        f"INTER_STAGE_DELAY_CYCLES={inter_stage_delay}",
        "-o",
        str(out),
    ]
    compile_cmd.extend(str(ROOT / src) for src in RTL_SOURCES)
    subprocess.run(compile_cmd, cwd=REPO, check=True, capture_output=True, text=True)
    sim = subprocess.run(["vvp", str(out)], cwd=REPO, check=True, capture_output=True, text=True)
    match = INFO_RE.search(sim.stdout)
    if not match:
        raise RuntimeError(
            f"missing INFO line for K={num_stages}, D={data_width}, "
            f"delay={inter_stage_delay}\n{sim.stdout}"
        )
    wavefront = int(match.group("wavefront"))
    fullwait = int(match.group("fullwait"))
    saved = int(match.group("saved"))
    return {
        "num_stages": num_stages,
        "data_width": data_width,
        "inter_stage_delay": inter_stage_delay,
        "wavefront": wavefront,
        "fullwait": fullwait,
        "saved": saved,
        "speedup": fullwait / wavefront,
    }


def parse_cases(raw_cases: list[str]) -> list[tuple[int, int, int]]:
    cases: list[tuple[int, int, int]] = []
    for raw in raw_cases:
        parts = raw.lower().split("x")
        if len(parts) == 2:
            k_s, d_s = parts
            f_s = "0"
        elif len(parts) == 3:
            k_s, d_s, f_s = parts
        else:
            raise ValueError(f"bad case '{raw}', expected KxD or KxDxF")
        cases.append((int(k_s), int(d_s), int(f_s)))
    return cases


def write_report(rows: list[dict[str, int | float | str]]) -> pathlib.Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report = OUT_DIR / "wavefront_digit_stream_sweep.md"
    lines = [
        "# Wavefront Digit-Stream Sweep",
        "",
        "This report is generated by `run_wavefront_digit_stream_sweep.py`.",
        "It uses the same directed radius-1 multistage cluster testbench and",
        "compares a live wavefront pipeline against a sequential full-wait",
        "reference that restarts one complete stage at a time.",
        "",
        "| stages K | data width D | inter-stage delay | wavefront cycles | full-wait cycles | saved cycles | speedup |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['num_stages']} | {row['data_width']} | "
            f"{row['inter_stage_delay']} | {row['wavefront']} | "
            f"{row['fullwait']} | {row['saved']} | {row['speedup']:.3f}x |"
        )
    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- Speedup grows with the number of streamed solver stages because the",
            "  full-wait reference pays the row-engine fill/drain cost at every",
            "  stage boundary.",
            "- The wavefront path still runs all digits; it is not an early-stop or",
            "  reduced-precision result.",
            "- This is an Icarus functional/cycle checkpoint only.  Runtime mode3",
            "  integration and U55C route are still required before claiming a",
            "  routed solver-level throughput result.",
            "",
        ]
    )
    report.write_text("\n".join(lines), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--case",
        action="append",
        default=["2x8", "4x8", "8x8", "4x11", "8x11", "4x8x1", "8x11x1"],
        help="case formatted as KxD or KxDxF, for example 4x8 or 4x8x1",
    )
    args = parser.parse_args()
    rows = [run_case(k, d, f) for k, d, f in parse_cases(args.case)]
    report = write_report(rows)
    for row in rows:
        print(
            f"K={row['num_stages']} D={row['data_width']} "
            f"delay={row['inter_stage_delay']} "
            f"wavefront={row['wavefront']} fullwait={row['fullwait']} "
            f"speedup={row['speedup']:.3f}x"
        )
    print(f"Wrote {report.relative_to(REPO)}")


if __name__ == "__main__":
    main()
