#!/usr/bin/env python3
"""Run strict prior-fractional PageRank wavefront stage sweeps.

This is the strictest current check for solver-level digit streaming:
the original MSDF_MUL_ADD_8 prior operator is instantiated once per
row/stage, and committed output digits from stage k feed stage k+1 directly.
The test is standalone by design; it excludes runtime loader/cert overhead.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
ITER = ROOT / "MSDF_iterative_solver"
SRC = ROOT / "MSDF_operator_srcs/MSDF_Operators/MSDF_Operators/MSDF_Operators.srcs/sources_1/new"
REPORT = ITER / "generated/prior_fractional_wavefront_sweep.md"

ORIG_SOURCES = [
    "DFF.v",
    "full_adder.v",
    "parallel_online_adder_block.v",
    "parallel_online_adder.v",
    "parallel_online_adder_4.v",
    "parallel_online_adder_4_with_obuf.v",
    "vector_append.v",
    "selector.v",
    "append_and_select.v",
    "output_and_update.v",
    "MSDF_MUL_ADD_8.v",
]

COUNTER_RE = re.compile(
    r"COUNTERS prior_wavefront K=(?P<k>\d+) total=(?P<total>\d+) "
    r"capture=(?P<capture>\d+) stage_counts=(?P<stage_counts>[0-9a-fA-F]+) "
    r"overlap=(?P<overlap>[01xXzZ]+)"
)


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, check=True, capture_output=True, text=True)


def run_case(k: int) -> dict[str, int | str | float]:
    run([
        sys.executable,
        "MSDF_iterative_solver/make_pagerank_prior_fractional_vectors.py",
        "--num-iters",
        str(k),
    ])
    out = pathlib.Path("/tmp") / f"tb_prior_fractional_wavefront_k{k}.vvp"
    compile_cmd = [
        "iverilog",
        "-g2012",
        "-I",
        "MSDF_iterative_solver/tb",
        f"-DPRIOR_WAVEFRONT_STAGES_VALUE={k}",
        "-o",
        str(out),
        *[str(SRC / name) for name in ORIG_SOURCES],
        "MSDF_iterative_solver/rtl/iter_fixed_degree_template_unpack.v",
        "MSDF_iterative_solver/prior_rtl/iter_prior_online_mma8_row_kernel.v",
        "MSDF_iterative_solver/prior_rtl/iter_prior_online_mma8_stream_stage_cluster.v",
        "MSDF_iterative_solver/prior_rtl/iter_prior_online_mma8_global_wavefront_top.v",
        "MSDF_iterative_solver/tb/tb_iter_prior_online_mma8_global_wavefront_top.v",
    ]
    run(compile_cmd)
    sim = run(["vvp", str(out)])
    match = COUNTER_RE.search(sim.stdout)
    if not match:
        raise RuntimeError(f"missing counter line for K={k}\n{sim.stdout}")
    total = int(match.group("total"))
    capture = int(match.group("capture"))
    return {
        "k": k,
        "total": total,
        "capture": capture,
        "stage_counts": match.group("stage_counts"),
        "overlap": match.group("overlap"),
        "cycles_per_fused_iter": total / k,
        "stdout": sim.stdout.strip(),
    }


def write_report(rows: list[dict[str, int | str | float]]) -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Prior-Fractional PageRank Wavefront Sweep",
        "",
        "This report is generated by `run_prior_fractional_wavefront_sweep.py`.",
        "It uses the original `MSDF_MUL_ADD_8` operator and the strict",
        "`pagerank32_global_prior_fractional` fixture.  The test is standalone:",
        "it validates stage-to-stage digit streaming and excludes runtime",
        "loader/certification overhead.",
        "",
        "| K stages | total cycles | captured digits | cycles / fused iter | overlap flags | notes |",
        "| ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['k']} | {row['total']} | {row['capture']} | "
            f"{row['cycles_per_fused_iter']:.2f} | `{row['overlap']}` | "
            "final state matches fractional golden within <=4 LSB |"
        )
    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- `overlap=1...1` means each later stage starts before the previous stage has completed all committed digits.",
            "- The captured digit count stays at `DATA_WIDTH=14`, not `K*DATA_WIDTH`, so the cascade consumes one input word stream and propagates committed digits internally.",
            "- This proves the prior operator can be used in a solver-level digit-stream wavefront, but it is not yet a same-shell runtime result.",
            "- Next integration step: wrap this prior-fractional wavefront as a new runtime mode and add L1 certification on the last-stage delta.",
            "",
            "## Raw Outputs",
            "",
        ]
    )
    for row in rows:
        lines.extend(
            [
                f"### K={row['k']}",
                "",
                "```text",
                str(row["stdout"]),
                "```",
                "",
            ]
        )
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stages", type=int, action="append", default=[2, 3, 4])
    args = parser.parse_args()

    rows = [run_case(k) for k in args.stages]
    write_report(rows)
    for row in rows:
        print(
            f"K={row['k']} total={row['total']} capture={row['capture']} "
            f"cycles_per_fused_iter={row['cycles_per_fused_iter']:.2f} "
            f"overlap={row['overlap']}"
        )
    print(f"Wrote {REPORT}")


if __name__ == "__main__":
    main()
